### PR TITLE
Updates to the news section to introduce Dockstore blog

### PR DESCRIPTION
**Pull request by avani-k**

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]

**Comment by denis-yuen** [comment]
(confused this with dockstore-documentation)

**Review by denis-yuen — APPROVED** [review]
Are these changes relevant after the release?

**Comment by coverbeck** [comment]
> Are these changes relevant after the release?

Yes, it introduces the Dockstore blog. @avani-k is there any reason you didn't merge this?

**Comment by avani-k** [comment]
> > Are these changes relevant after the release?
> 
> Yes, it introduces the Dockstore blog. @avani-k is there any reason you didn't merge this?

I was just waiting for Denis's approval actually, needed 2 approvals for merging. But it fell off my radar actually and forgot to follow up with Denis. Now that I am looking at it, seems like I am not authorized to merge it. Could either @coverbeck or @denis-yuen do it? Or give me the permissions?

**Comment by avani-k** [comment]
> > > Are these changes relevant after the release?
> > 
> > 
> > Yes, it introduces the Dockstore blog. @avani-k is there any reason you didn't merge this?
> 
> I was just waiting for Denis's approval actually, needed 2 approvals for merging. But it fell off my radar actually and forgot to follow up with Denis. Now that I am looking at it, seems like I am not authorized to merge it. Could either @coverbeck or @denis-yuen do it? Or give me the permissions?

Just to recap: We already merged with develop a few weeks ago and it looks fine on [https://dev.dockstore.net/](https://dev.dockstore.net/)

**Comment by coverbeck** [comment]
I merged. That's odd, you should have had permissions, but I didn't look into it.

**Pull request merged**
